kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 32000
        hostPort: 32000
        protocol: TCP
      - containerPort: 80
        hostPort: 80
        protocol: TCP
      - containerPort: 443
        hostPort: 443
        protocol: TCP
    labels:
      ingress-ready: "true"
      juno-innovations.com/workstation: true
      topology.kubernetes.io/region: us-east-1
      node.kubernetes.io/instance-type: t3.xlarge
      topology.kubernetes.io/zone: us-east-1a
      eks.amazonaws.com/capacityType: SPOT
      juno-innovations.com/service: true
