{{- if and .Values.active .Values.terra.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: terra
  namespace: {{ .Values.namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: terra
  minReplicas: {{ .Values.mars.autoscaling.min_replicas }}
  maxReplicas: {{ .Values.mars.autoscaling.min_replicas }}
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 30
    scaleUp:
      stabilizationWindowSeconds: 30
  metrics:
    - type: ContainerResource
      containerResource:
        name: cpu
        container: terra
        target:
          type: Utilization
          averageUtilization: 50
{{- end }}
