{{- if .Values.active }}
apiVersion: v1
kind: Service
metadata:
  name: terra
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: terra
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: endpoint
{{- end }}
