apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: orion-hubble-{{ .Values.show }}
  namespace: argocd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: orion-hubble-{{ .Values.show }}
subjects:
  - kind: ServiceAccount
    name: orion-hubble
    namespace: {{ .Values.namespace }}
