apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: hubble
  namespace: "{{ .Values.namespace }}"
spec:
  parentRefs:
    - name: "{{ .Values.gateway_name }}"
      namespace: "{{ .Values.gateway_namespace }}"
      sectionName: https
  hostnames:
    - "{{ .Values.host }}"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: hubble
          port: 3000
      filters:
        - type: ExtensionRef
          extensionRef:
            group: traefik.io
            kind: Middleware
            name: "hsts-headers"
    - matches:
        - path:
            type: PathPrefix
            value: /socket.io
      backendRefs:
        - name: hubble
          port: 8000
      filters:
        - type: ExtensionRef
          extensionRef:
            group: traefik.io
            kind: Middleware
            name: "hsts-headers"
