{{- if .Values.active }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: {{ .Release.Namespace }}
  name: hubble-ingress
spec:
  {{- if .Values.ingressClassName }}
  ingressClassName: "{{ .Values.ingressClassName }}"
  {{- end }}
  rules:
    - http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: hubble
                port:
                  number: 3000
      {{- if .Values.host }}
      host: {{ .Values.host }}
      {{- end }}
{{- end }}
