{{- if and .Values.ingress.enabled .Values.active }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: {{ .Release.Namespace }}
  name: hubble-ingress
  annotations:
{{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: "{{ $value }}"
{{- end }}
spec:
  {{- with .Values.ingress.className | default .Values.ingressClassName }}
  ingressClassName: "{{ . }}"
  {{- end }}
  rules:
    - http:
        paths:
          {{- $hostIsIP := eq (include "hubble.hostIsIP" .) "true" }}
          {{- $usePrefix := eq (include "hubble.usePathPrefix" .) "true" }}
          - path: "/{{ if $usePrefix }}{{ .Release.Namespace }}{{ end }}"
            pathType: Prefix
            backend:
              service:
                name: hubble
                port:
                  number: 3000
      {{- if and .Values.host (not $hostIsIP) }}
      host: "{{ .Values.host }}"
      {{- end }}
{{- end }}
