{{- if .Values.active }}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: hubble-network-policy
  namespace: {{ .Values.namespace }}
spec:
  policyTypes:
    - Egress
  podSelector:
    matchLabels:
      app: hubble
  egress:
    - to:
      - ipBlock:
          cidr: 0.0.0.0/0  # Allow outbound traffic for authentication services and API
{{- end }}
