---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: orion-hubble-{{ .Values.show }}
  namespace: {{ .Values.namespace }}
rules:
- apiGroups: [""]
  resources: ["serviceaccounts/token"]
  verbs: ["create"]
