{{- if .Values.active }}
apiVersion: v1
kind: Service
metadata:
  name: hubble
  namespace: {{ .Values.namespace }}
spec:
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 600
  selector:
    app: hubble
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: endpoint
{{- end }}
