---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: orion-hubble-users-reader-{{ .Release.Namespace }}
rules:
- apiGroups: ["juno-innovations.com"]
  resources: ["users"]
  verbs: ["list", "get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: orion-hubble-users-reader-binding-{{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: orion-hubble-users-reader-{{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: orion-hubble
  namespace: {{ .Release.Namespace }}
