apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: workstations.junovfx.com
spec:
  group: junovfx.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - label
                - tag
                - group
                - repo
                - cpu
                - ram
              properties:
                label:
                  type: string
                registry:
                  type: string
                tag:
                  type: string
                group:
                  type: string
                repo:
                  type: string
                icon:
                  type: string
                  default: "https://junovfx.com/dog.png"
                gpu:
                  type: boolean
                cpu:
                  type: string
                ram:
                  type: string

  scope: Namespaced
  names:
    plural: workstations
    singular: workstation
    kind: Workstation
