{{- if .Values.active }}
apiVersion: v1
kind: Service
metadata:
  name: shows-db
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: shows-db
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
      name: db-port
---
apiVersion: v1
kind: Service
metadata:
  name: luna
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: luna
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: endpoint
{{- end }}
