{{- if and (eq .Values.active "true") (eq .Values.luna.enabled "true") }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mars-role-binding
subjects:
  - kind: ServiceAccount
    name: mars
roleRef:
  kind: Role
  name: mars-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}
