{{- if and .Values.active .Values.luna.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mars
  namespace: {{ .Values.namespace }}
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: mars

  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 50%
    type: RollingUpdate

  template:
    metadata:
      annotations:
        # Allow for footprint consolidation
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
      labels:
        app: mars

    spec:
      priorityClassName: juno-normal
      serviceAccountName: mars
      {{- if .Values.mars.node_selector.enable }}
      nodeSelector:
        {{- range $key, $value := .Values.mars.node_selector.labels }}
        {{ $key }}: {{ $value }}
        {{- end }}
      {{- end }}

      {{- if .Values.image_pull_secret }}
      imagePullSecrets:
        - name: {{ .Values.image_pull_secret }}
      {{- end }}

      containers:
        - name: mars
          image: {{.Values.registry}}/{{ .Values.mars.image }}
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: "/.health"
              port: 8000
            periodSeconds: 5
            failureThreshold: 2
          startupProbe:
            httpGet:
              path: "/.health"
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 5
            failureThreshold: 2
          resources:
            requests:
              cpu: 100m
              memory: 200Mi
          env:
            - name: SHOW
              value: {{ .Values.show }}
          ports:
            - containerPort: 8000
              name: endpoint
          volumeMounts:
            {{- range .Values.volumes }}
            - mountPath: {{ .mount_path }}
              name: {{ .name }}
              subPath: {{ .sub_path }}
            {{- end }}
      volumes:
        {{- range .Values.volumes }}
        - name: {{ .name }}
          persistentVolumeClaim:
            claimName: {{ .claim_name }}
        {{- end }}
{{- end }}
