{{- if and .Values.active .Values.luna.enabled }}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: mars-network-policy
  namespace: {{ .Values.namespace }}
spec:
  policyTypes:
    - Egress
  podSelector:
    matchLabels:
      app: mars
  egress:
    - to:
      - ipBlock:
          cidr: 0.0.0.0/0  # Allow outbound traffic for storage transactions
{{- end }}
