{{- if and .Values.active .Values.luna.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mars-role
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "update", "patch", "create", "delete"]
{{- end }}
