registry: junoinnovations             # Registry to pull the Orion images from
guid:                                 # GUID of the project
host:                                 # Hostname of the project
ingressClassName: nginx
active: true                          # Whether the project is active
image_pull_secret:                    # Image pull secret to use for the project. This is the name of the secret in the namespace
genesis_proxy: true                   # Whether to use the Genesis proxy
genesis_namespace: argocd             # Namespace where Genesis is deployed
http_scheme: https
nextauth_url_tpl: "{{ .Values.http_scheme }}://{{ .Values.host }}/api/auth"
workload_sharing: false               # Setting True will enable the ability for users to share workloads with other users
cert_manager_issuer: letsencrypt-prod

kuiper:
  tolerations: []
  image: kuiper:v4.1.3                # Image to pull for Kuiper
  node_selector:                      # Node selector to deploy the Kuiper server to
    enable: true                      # Enable node selector
    labels:                           # Node selector to deploy the Kuiper server to
      juno-innovations.com/service: "true"
  replicas: 1                         # Pinned — no HPA
  resources:
    requests:
      cpu: 350m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 512Mi

hubble:
  tolerations: []
  image: hubble:v6.0.1              # Image to pull for Hubble
  env: {}                             # Environment variables to set for the Hubble server
  node_selector:                      # Node selector to deploy the Hubble server to
    enable: true                      # Enable node selector
    labels:                           # Node selector to deploy the Hubble server to
      juno-innovations.com/service: "true"
  autoscaling:
    min_replicas: 1                   # Minimum number of replicas to run
    max_replicas: 5                   # Maximum number of replicas to run
  resources:
    requests:
      cpu: 350m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 1Gi

rhea:
  image: rhea:v1.2.3                # Image to pull for Rhea
  env: {}                            # Environment variables to set for the Rhea server
  resources:
    requests:
      cpu: 5m
      memory: 24Mi
    limits:
      cpu: 50m
      memory: 64Mi

resourceQuota:
  enabled: false
  hard:
    cpu_request: "16"
    memory_request: "32Gi"
    cpu_limit: "32"
    memory_limit: "64Gi"
