{{- if and .Values.active .Values.luna.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mercury
  namespace: {{ .Values.namespace }}
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: mercury

  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 50%
    type: RollingUpdate

  template:
    metadata:
      annotations:
        # Allow for footprint consolidation
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
      labels:
        app: mercury

    spec:
      serviceAccountName: mercury

      {{- if .Values.mercury.node_selector.enable }}
      nodeSelector:
        {{- range $key, $value := .Values.mercury.node_selector.labels }}
        {{ $key }}: {{ $value }}
        {{- end }}
      {{- end }}
      {{- if .Values.image_pull_secret }}
      imagePullSecrets:
        - name: {{ .Values.image_pull_secret }}
      {{- end }}
      containers:
        - name: mercury
          image: {{.Values.registry}}/{{ .Values.mercury.image }}
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: "/.health"
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 5
            failureThreshold: 2
          startupProbe:
            httpGet:
              path: "/.health"
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 5
            failureThreshold: 2
          ports:
            - containerPort: 8000
              name: endpoint
          resources:
            requests:
              cpu: 750m
              memory: 200Mi
{{- end }}
