apiVersion: v1
kind: Service
metadata:
  name: mercury
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: mercury
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: endpoint
