{{- if .Values.active }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: titan
  namespace: {{ .Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: titan
subjects:
  - kind: ServiceAccount
    name: titan
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: titan-{{ .Values.namespace }}
  namespace: {{ .Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: titan-{{ .Values.namespace }}
subjects:
  - kind: ServiceAccount
    name: titan
    namespace: {{ .Values.namespace }}
{{- end }}
