{{- if .Values.active }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: titan
  namespace: {{ .Values.namespace }}
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: titan

  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 50%
    type: RollingUpdate

  template:
    metadata:
      labels:
        app: titan

    spec:
      serviceAccountName: titan

      {{- if .Values.titan.node_selector.enable }}
      nodeSelector:
        {{- range $key, $value := .Values.titan.node_selector.labels }}
        {{ $key }}: {{ $value }}
        {{- end }}
      {{- end }}

      containers:
        - name: titan
          imagePullPolicy: Always
          image: {{.Values.registry}}/{{ .Values.titan.image }}
          env:
            - name: ORION_OWNER
              value: {{ .Values.titan.owner }}
            - name: ORION_EMAIL
              value: {{ .Values.titan.email }}
            - name: PROJECT
              value: {{lower .Values.show }}
            - name: PROJECT_GUID
              value: "{{ .Values.guid }}"
          resources:
            requests:
              cpu: 500m
              memory: 200Mi
          ports:
            - containerPort: 8000
              name: endpoint
{{- end }}
