{{- if .Values.active }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: titan
  namespace: {{ .Values.namespace }}
rules:
  - apiGroups: [""]
    resources: ["pods", "services"]
    verbs: ["list", "get"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["list", "get", "create", "delete", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: titan-{{ .Values.namespace }}
rules:
  # Titan is now allowed to create its own CRD's as to fix delivery issues for them.
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["list", "get", "create", "delete", "patch", "update"]
  # legacy for the old CRD's. TODO: We will want to remove this eventually.
  - apiGroups: ["junovfx.com"]
    resources: ["groups", "users"]
    verbs: ["list", "create", "delete", "get", "patch", "update"]
  # target CRD's.
  - apiGroups: ["juno-innovations.com"]
    resources: ["groups", "users"]
    verbs: ["list", "create", "delete", "get", "patch", "update"]
{{- end }}
