{{- if .Values.genesis_proxy }}
apiVersion: v1
kind: Service
metadata:
  name: terra
  namespace: {{ .Values.namespace }}
spec:
  type: ExternalName
  externalName: terra.{{ .Values.genesis_namespace }}.svc.cluster.local
  ports:
    - port: 8000
      targetPort: 8000
{{- end }}
