{{- if .Values.genesis_proxy }}
apiVersion: v1
kind: Service
metadata:
  name: titan
  namespace: {{ .Values.namespace }}
spec:
  type: ExternalName
  externalName: titan.argocd.svc.cluster.local
  ports:
    - port: 8000
      targetPort: 8000
{{- end }}
