apiVersion: v1
kind: ConfigMap
metadata:
  name: orion-environment-systempolicy
  namespace: {{ .Values.namespace }}
  labels:
    juno.cedar.system: "true"
data:
  policies.cedar: |-
{{ tpl (.Files.Get "files/rhea/system-policies.cedar") . | indent 4 }}
