{{- if and (eq .Values.active "true") (eq .Values.luna.enabled "true") }}
apiVersion: v1
kind: Service
metadata:
  name: webb
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: webb
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: endpoint
{{- end }}
