{{- if and .Values.active .Values.luna.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: webb
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: webb
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: endpoint
{{- end }}
