{{- if .Values.active }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kuiper
  namespace: {{ .Values.namespace }}
rules:
  - apiGroups: [""]
    resources: ["serviceaccounts/token"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kuiper-kuiper
  namespace: {{ .Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kuiper
subjects:
  - kind: ServiceAccount
    name: kuiper
    namespace: {{ .Values.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kuiper-cluster-admin
  namespace: {{ .Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: kuiper
    namespace: {{ .Values.namespace }}

{{- end }}
