apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kuiper-{{ .Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kuiper-{{ .Values.namespace }}
subjects:
  - kind: ServiceAccount
    name: kuiper
    namespace: {{ .Values.namespace }}
