apiVersion: apps/v1
kind: Deployment
metadata:
  name: debug
  namespace: {{ .Values.namespace }}
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: debug

  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 50%
    type: RollingUpdate

  template:
    metadata:
      labels:
        app: debug

    spec:
      serviceAccountName: kuiper
      containers:
        - name: kuiper
          image: alpine
          command: [ "/bin/ash", "-c", "--" ]
          args: [ "while true; do sleep 30; done;" ]
