{{- if .Values.active }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: kuiper
  namespace: {{ .Values.namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: kuiper
  minReplicas: {{ .Values.kuiper.autoscaling.min_replicas }}
  maxReplicas: {{ .Values.kuiper.autoscaling.max_replicas }}
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 30
    scaleUp:
      stabilizationWindowSeconds: 30
  metrics:
    - type: ContainerResource
      containerResource:
        name: cpu
        container: kuiper
        target:
          type: Utilization
          averageUtilization: 50
{{- end }}
