{{- if and .Values.active .Values.kuiper.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kuiper
  namespace: {{ .Values.namespace }}
rules:
  # Kuiper is now allowed to create its own CRD's as to fix delivery issues for them.
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["list", "get", "create", "delete", "patch", "update"]
  # legacy for the old CRD's. TODO: We will want to remove this eventually.
  - apiGroups: ["junovfx.com"]
    resources: ["workstations"]
    verbs: ["list", "create", "delete", "get", "patch", "update"]
  # target CRD's.
  - apiGroups: ["juno-innovations.com"]
    resources: ["workstations", "workstation-logs"]
    verbs: ["list", "create", "delete", "get", "patch", "update"]
{{- end }}
