apiVersion: v1
kind: Service
metadata:
  name: kuiper
  namespace: {{ .Values.namespace }}
  annotations:
    linkerd.io/inject: enabled
spec:
  selector:
    app: kuiper
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: endpoint
