{{- if .Values.active }}
apiVersion: v1
kind: Service
metadata:
  name: kuiper
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: kuiper
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: endpoint
{{- end }}
