apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: users.juno-innovations.com
spec:
  group: juno-innovations.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                uid:
                  type: integer
                email:
                  type: string
  scope: Cluster
  names:
    plural: users
    singular: user
    kind: User
    shortNames:
    - u
