name: PR Message

on:
  pull_request:
    types:
      - review_requested

jobs:
  google-chat-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout CI repository
        uses: actions/checkout@v4
        with:
          repository: juno-fx/ci
          path: .juno-ci
          token: ${{ secrets.RO_CI_REPO_TOKEN }}
      - name: Run Google Chat notification
        uses: ./.juno-ci/.github/actions/pr-gChat-notification
