name: PR Message

on:
  pull_request:
    types:
      - review_requested

jobs:
  google-chat-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout CI repository
        uses: actions/checkout@v4
        with:
          repository: juno-fx/ci
          ref: 204-public-repo-access-failure
          path: .juno-ci
          token: ${{ secrets.RO_CI_REPO_TOKEN }}
      - name: Run Google Chat notification
        uses: ./.juno-ci/.github/actions/workflow/pr-gChat-notification
        with:
          webhookUrl: ${{ secrets.GCHAT_PR_SPACE }}
          title: ${{ github.repository }}
          subtitle: ${{ github.head_ref }}
          additionalSections: '[{"header": "Requested Reviewer", "widgets": [{"decoratedText": {"text": "${{ github.event.requested_reviewer.login }}", "icon": {"knownIcon": "PERSON"}}}}]'
